# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 00:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('anotacao', models.TextField()),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('dataEHoraDeInicio', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=20)),
                ('uf', models.CharField(max_length=2)),
                ('endereco', models.CharField(max_length=20)),
                ('cep', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='AgendaInstitucinal',
            fields=[
                ('agendamain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='agenda.AgendaMain')),
                ('nome', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Empresa', to='agenda.Empresa')),
            ],
            bases=('agenda.agendamain',),
        ),
        migrations.CreateModel(
            name='AgendaPrivada',
            fields=[
                ('agendamain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='agenda.AgendaMain')),
                ('tipo', models.CharField(max_length=100)),
            ],
            bases=('agenda.agendamain',),
        ),
        migrations.CreateModel(
            name='AgendaPublica',
            fields=[
                ('agendamain_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='agenda.AgendaMain')),
                ('tipo', models.CharField(max_length=100)),
            ],
            bases=('agenda.agendamain',),
        ),
        migrations.AddField(
            model_name='usuario',
            name='agenda',
            field=models.ManyToManyField(blank=True, to='agenda.AgendaMain'),
        ),
        migrations.AddField(
            model_name='agendamain',
            name='compromisso',
            field=models.ManyToManyField(blank=True, to='agenda.Compromisso'),
        ),
    ]
